### ISSUE TITLE
Make classes of GridView sort links configurable

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#10227]
Current implementation:

```php
$class = $direction === SORT_DESC ? 'desc' : 'asc';
```

And there is no way to add your custom class. I want to use Font Awesome icons.

**Comment by arogachev** [comment]
My bad, missed that `$sortLinkOptions` exists in `yii\grid\DataColumn`.

**Comment by arogachev** [comment]
This is how link rendered:

```php
return $sort->link($this->attribute, array_merge($this->sortLinkOptions, ['label' => ($this->encodeLabel ? Html::encode($label) : $label)]));
```
But using `$sortLinkOptions` doesn't solve the problem, because even I can set main class like `fa`, I'm unable to set classes like `fa-sort-amount-asc` and `fa-sort-amount-desc`.

**Comment by SilverFire** [comment]
We are talking about [DataColumn.php:142](https://github.com/yiisoft/yii2/blob/master/framework/grid/DataColumn.php#L142).

`$sort` is an instance of [`yii\data\Sort`](https://github.com/yiisoft/yii2/blob/master/framework/data/Sort.php). There is a [`link()`](https://github.com/yiisoft/yii2/blob/master/framework/data/Sort.php#L295) method and you can override it do satisfy your requirements.

By default `link()` method adds class `asc` or `desc` to the link, so it may be solved with CSS:

```scss
.link-sorter {
    .asc { 
        @extend .fa-sort-amount-asc;
    }

    .desc { 
        @extend .fa-sort-amount-desc;
    }
}
```

Do you have any ideas, how to make it better?

**Comment by arogachev** [comment]
Yes I already tried something like that, but with Font Awesome we need to append content like `<i class="fa ..."></i>` depending on sort direction. And seems like it's not possible without extending framework classes and overriding core methods.

**Comment by arogachev** [comment]
Actually we can use after pseudo class like it's done in advanced template.

**Comment by Alex-Code** [comment]
I'd do something like
```php
class Sort extends Object
{
    public $sortClassAsc = 'asc';
    public $sortClassDesc = 'desc';
    //....
    public function link($attribute, $options = [])
    {
        //....
        $class = $direction === SORT_DESC ? $this->sortClassDesc: $this->sortClassAsc;
        //....
    }
    //....
}
```
or
```php
class Sort extends Object
{
    public $sortClasses = [
        SORT_ASC => 'asc',
        SORT_DESC => 'desc'
    ];
    //....
    public function link($attribute, $options = [])
    {
        //....
        $class = $this->sortClasses[$direction];
        //....
    }
    //....
}
```

**Comment by arogachev** [comment]
I came up with this workaround. I'm using SASS.

This is duplicate of `.fa` class from generated Font Awesome CSS (I don't want to import whole file because it's already included in main asset).

```sass
%fa {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

`GridView` customization:

// GridView

```sass
.grid-view {  
  th {  
    a {
      &:after {
        @extend %fa;
        position: relative;
        left: 5px;
      }
    }

    .asc {
      &:after {
        content: "\f161";
      }
    }

    .desc {
      &:after {
        content: "\f161";
      }
    }
  }
}
```

The content for actual icons are copied from generated Font Awesome CSS as well:

```css
.fa-sort-amount-asc:before {
  content: "\f160";
}

.fa-sort-amount-desc:before {
  content: "\f161";
}
```

**Comment by SilverFire** [comment]
@arogachev when you're using SASS, you can use `@extend` to inherit `.asc` and `.desc` icon from FA

**Comment by arogachev** [comment]
@SilverFire Yes, but how we can include Font Awesome without adding it to the rest of the code? Because it's included in main asset bundle `AppAsset`.

**Comment by SilverFire** [comment]
@arogachev never mind, my fault. You can't indeed.

**Comment by SilverFire** [comment]
I'm closing this issue because you have two ways to override default conduction of link and both of them are OK.

**Comment by arogachev** [comment]
What do you think about adding it to cookbook, @samdark?

**Comment by samdark** [comment]
I'm OK with it if you could help with a pull request.

**Comment by arogachev** [comment]
@samdark OK, i will send it later.

**Comment by dharmendraprajapatii** [comment]
You can configure your link like this

<a href='<?= $dataProvider->sort->createUrl( "name" ) ?>'> Name <i class="fa fa-sort-alpha-asc"></i> </a>

**Comment by dharmendraprajapatii** [comment]
You can configure your link like this

`<a href='<?= $dataProvider->sort->createUrl( "name" ) ?>'> Name <i class="fa fa-sort-alpha-asc"></i> </a>`

**Comment by marcovtwout** [comment]
Here's a few SASS-solutions for FontAwesome 5 icons without modifying the grid view configuration or duplicating icon code:

Icon before label:

```scss
a[data-sort] {
    &:before {
        @extend .fa;
        margin-right: 5px;
    }

    &.desc {
        @extend .fa-sort-down;
    }
    &.asc {
        @extend .fa-sort-up;
    }
}
```

Icon behind label:

```scss
a[data-sort] {
    position: relative;
    padding-right: 12px;

    &:before {
        @extend .fa;
        position: absolute;
        right: 0;
    }

    &.desc {
        @extend .fa-sort-down;
    }
    &.asc {
        @extend .fa-sort-up;
    }
}
```

Always show a default icon, and highlight icon on active column:

```scss
a[data-sort] {
    @extend .fa-sort;

    &:before {
        @extend .fa;
        margin-right: 5px;
        color: #bbb;
    }

    &.asc, &.desc {
        &:before {
            color: #f00;
        }
    }
    &.desc {
        @extend .fa-sort-down;
    }
    &.asc {
        @extend .fa-sort-up;
    }
}
```
