### ISSUE TITLE
doc for codeception set up is out-of-date

### ISSUE THREAD

**Issue by haoliang-gao** [yiisoft/yii2#11572]
out-of-date where: current newest codeception version is not `2.0.*`

Accroding to codeception official document, it's newest version is 2.1,  and default document displayed is 2.1 ( with no text to mark the doc is for 2.1 ).

But, Yii doc still write:

> composer require "codeception/codeception=2.0.*"
> composer require "codeception/specify=*"
> composer require "codeception/verify=*"
>
> http://www.yiiframework.com/doc-2.0/guide-test-environment-setup.html

That has spend me ONE hour to find out it which makes me so depressed.

Please update that section to date.

**Comment by samdark** [comment]
2.0 was failing to you?

**Comment by haoliang-gao** [comment]
2.0, 2.1 is version of codeception.

Yes, 2.0 was failing to me.

Configuration between 2.0 and 2.1 is different:

2.1:

```yaml
modules:
   enabled:
       - REST:
           depends: PhpBrowser
           url: 'http://serviceapp/api/v1/'
```

ref: http://codeception.com/docs/modules/REST#.Vzp0zRwvDft

2.0:

```yaml
modules:
   enabled: [PhpBrowser, REST]
   config:
      PhpBrowser:
         url: http://serviceapp/
      REST:
         url: 'http://serviceapp/api/v1/'
```

ref: https://github.com/Codeception/Codeception/blob/2.0/docs/modules/REST.md#configuration

----

I have checked 2.0.8 yii-app-advanced, It's readme updated to 2.1:

> composer global require "codeception/codeception=2.1.*" "codeception/specify=*" "codeception/verify=*"
> ref https://github.com/yiisoft/yii2-app-advanced/blob/master/tests/README.md

So, the issue is only for yiisoft/yii2 repo's doc.
