### ISSUE TITLE
Assets strange behaviour

### ISSUE THREAD

**Issue by kybarg** [yiisoft/yii2#11828]
Started new project using yii2-advanced-app template with Vagrant;
If new code is longer then old it adds strange symbols to complete file length. If new code is shorter - in browser i see old code but with same length. Tried to restart Vagrant. Nothing helps.

In editor:
```css
body {
    background-color: #FAFAFA;
}

.card {
    background-color: #ffffff;
    border-radius: 2px;
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.2),0 1px 1px 0 rgba(0,0,0,.14),0 2px 1px -1px rgba(0,0,0,.12);
    color: rgba(0,0,0,0.87);
}
```

In browser:
```css
body {
	background-color: #000;
}
�����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

Dont know what causes such behaviour. Currently on Windows 10, yii2-advanced-app 2.0.8 on Vagrant. 

# Update!!!
Can be closed.
It was nginx issue. Should set `sendfile off` in **nginx.conf**
