### ISSUE TITLE
Using codeception for testing console command functional

### ISSUE THREAD

**Issue by vinpel** [yiisoft/yii2#13574]
### What steps will reproduce the problem?
I have made a complex yii command and i want to be able to test with codeception the whole process.
How  can i do that ???

### What is the expected result?
I want do be able to catch output of command, grabRecord ...

### What do you get instead?
no console mention in yii2 codeception module

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.6
| Operating system | Alpine Linux 3.5

**Comment by vinpel** [comment]
when trying to use the functional test (more logic) it get the following error :

command :
```bash
./codecept -vvv run functional 'DistantControllerCest' -c modules/service
```

Error :
```bash
1) DistantControllerCest: Check open
 Test  tests/functional/DistantControllerCest.php:checkOpen

  [InjectionException] Failed to inject dependencies in instance of 'module\service\tests\functional\DistantControllerCest'. Class frontend\tests\FunctionalTester does not exist
```

__File modules\service\tests\functional\DistantControllerCest.php__
```php
<?php
namespace module\service\tests\functional;
use module\service\tests\FunctionalTester;
/**
* basic test
*/
class DistantControllerCest
{
  /**
  * Test l'affichage de base du site
  */
  public function checkOpen(FunctionalTester $I)
  {
    //$I->amOnPage('/');
    //$I->see('identification','h2');
  }
}

```
__File :modules\service\codeception.yml__
```yaml
namespace: modules\service\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: '../../console/config/test-local.php'

```
__file  modules\service\tests\functional.suite.yml__

```
class_name: FunctionalTester
modules:
    enabled:
        - Filesystem
        - Yii2
        - Asserts

```
