### ISSUE TITLE
Class m160313_153426_session_init does not exist in /var/www/html/framework/di/Container.php

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15722]
### What steps will reproduce the problem?
try 
 ```sh
docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint /repo/vendor/bin/phpunit php
```
```yml
# Local run unit tests
# for docker-compose CLI like this manual https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/
#
# Important: run `composer install` before first time use
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint composer php update -vvv
#
# run directly (can't terminate)
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint /repo/vendor/bin/phpunit php
#
# use shell
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint bash php
# /repo/vendor/bin/phpunit

version: '2'
services:
  php:
    image: bscheshir/codeception:php7.2.2-fpm-alpine-yii2 #contain phpunit
    volumes:
      - ./yii2/tests/data/config-docker.php:/var/www/html/tests/data/config.php # use named connection for db
      - ./yii2:/var/www/html #src and tests shared to container
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
    depends_on:
      - pgsql
      - mysql
# example for pgsql
# also add ./tests/data/config.local.php
# <?php
# $config['databases']['pgsql']['dsn'] = 'pgsql:host=pgsql;port=5432;dbname=yii2advanced';
# $config['databases']['pgsql']['username'] = 'yii2advanced';
# $config['databases']['pgsql']['password'] = 'yii2advanced';
  pgsql:
    image: postgres:10.2
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yiitest
      POSTGRES_USER: postgres
    networks:
      default:
        aliases:
         - postgres
  mysql:
    image: mysql:8.0.3
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yiitest
      MYSQL_USER: travis
      MYSQL_PASSWORD: travis

```
### What is the expected result?
no errors

### What do you get instead?
```sh
docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint /repo/vendor/bin/phpunit php
Starting projects_pgsql_1 ... 
Starting projects_mysql_1 ... done
PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

.............................................................   61 / 6589 (  0%)
.............................................................  122 / 6589 (  1%)
.............................................................  183 / 6589 (  2%)
.............................................................  244 / 6589 (  3%)
.............................................................  305 / 6589 (  4%)
.............................................................  366 / 6589 (  5%)
.............................................................  427 / 6589 (  6%)
.............................................................  488 / 6589 (  7%)
.............................................................  549 / 6589 (  8%)
.................................................S...........  610 / 6589 (  9%)
.............................................................  671 / 6589 ( 10%)
...........................S.S.S.S.S.........................  732 / 6589 ( 11%)
.............................................................  793 / 6589 ( 12%)
..................SSSSSSSSSSSSSSSSSS....................F....  854 / 6589 ( 12%)
....................................SSSSSSSSSSSSSSSSSSSSSSSSS  915 / 6589 ( 13%)
SSSSSSSSSSS...................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  976 / 6589 ( 14%)
SSSSSSSSSSSSSSSSSSSSSSS...................................... 1037 / 6589 ( 15%)
......................S...................................... 1098 / 6589 ( 16%)
............................................................. 1159 / 6589 ( 17%)
............................................................. 1220 / 6589 ( 18%)
...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1281 / 6589 ( 19%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1342 / 6589 ( 20%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1403 / 6589 ( 21%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1464 / 6589 ( 22%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1525 / 6589 ( 23%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1586 / 6589 ( 24%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1647 / 6589 ( 24%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1708 / 6589 ( 25%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1769 / 6589 ( 26%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1830 / 6589 ( 27%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1891 / 6589 ( 28%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 1952 / 6589 ( 29%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2013 / 6589 ( 30%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2074 / 6589 ( 31%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2135 / 6589 ( 32%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2196 / 6589 ( 33%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............................. 2257 / 6589 ( 34%)
............................................................. 2318 / 6589 ( 35%)
.................................................S........... 2379 / 6589 ( 36%)
..............................S.............E................ 2440 / 6589 ( 37%)
............................................................. 2501 / 6589 ( 37%)
.........................................................SS.. 2562 / 6589 ( 38%)
............................................................. 2623 / 6589 ( 39%)
..................................S..E.E..................... 2684 / 6589 ( 40%)
......F...................F...................F.............. 2745 / 6589 ( 41%)
...............S..................SSSSSSSSSSSSSSSSSSSSSSSSSSS 2806 / 6589 ( 42%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2867 / 6589 ( 43%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2928 / 6589 ( 44%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2989 / 6589 ( 45%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 3050 / 6589 ( 46%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 3111 / 6589 ( 47%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSSSSSS 3172 / 6589 ( 48%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 3233 / 6589 ( 49%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....... 3294 / 6589 ( 49%)
............................................................. 3355 / 6589 ( 50%)
............................................................. 3416 / 6589 ( 51%)
............................................................. 3477 / 6589 ( 52%)
................S............E............................... 3538 / 6589 ( 53%)
............................................................. 3599 / 6589 ( 54%)
............................................................. 3660 / 6589 ( 55%)
.........................S................................... 3721 / 6589 ( 56%)
...........................................S................. 3782 / 6589 ( 57%)
...........................F................................. 3843 / 6589 ( 58%)
............................................................. 3904 / 6589 ( 59%)
............................................................. 3965 / 6589 ( 60%)
............................................................. 4026 / 6589 ( 61%)
..............SSSS..........................S....S........... 4087 / 6589 ( 62%)
............S.......................SSS...................... 4148 / 6589 ( 62%)
............................................................S 4209 / 6589 ( 63%)
S.....SSS.................................................... 4270 / 6589 ( 64%)
.......................S...............S..................... 4331 / 6589 ( 65%)
............................................................. 4392 / 6589 ( 66%)
............................RR............................... 4453 / 6589 ( 67%)
............................................................. 4514 / 6589 ( 68%)
............................................................. 4575 / 6589 ( 69%)
............................................................. 4636 / 6589 ( 70%)
......................................................R...... 4697 / 6589 ( 71%)
............................................................. 4758 / 6589 ( 72%)
............................................................. 4819 / 6589 ( 73%)
............................................................. 4880 / 6589 ( 74%)
............................................................. 4941 / 6589 ( 74%)
............................................................. 5002 / 6589 ( 75%)
...................S......................................... 5063 / 6589 ( 76%)
............................................................. 5124 / 6589 ( 77%)
............................................................. 5185 / 6589 ( 78%)
............................................................. 5246 / 6589 ( 79%)
............................................................. 5307 / 6589 ( 80%)
..............I.............................................. 5368 / 6589 ( 81%)
............................................................. 5429 / 6589 ( 82%)
............................................................. 5490 / 6589 ( 83%)
.........................Yii Migration Tool (based on Yii v2.0.15-dev)

Total 3 migrations to be reverted:
	m170907_052038_rbac_add_index_on_auth_assignment_user_id
	m140506_102106_rbac_init
	m160313_153426_session_init

*** reverting m170907_052038_rbac_add_index_on_auth_assignment_user_id
    > drop index auth_assignment_user_id_idx on {{%auth_assignment}} ... done (time: 0.019s)
*** reverted m170907_052038_rbac_add_index_on_auth_assignment_user_id (time: 0.031s)

*** reverting m140506_102106_rbac_init
    > drop table {{%auth_assignment}} ... done (time: 0.035s)
    > drop table {{%auth_item_child}} ... done (time: 0.017s)
    > drop table {{%auth_item}} ... done (time: 0.039s)
    > drop table {{%auth_rule}} ... done (time: 0.030s)
*** reverted m140506_102106_rbac_init (time: 0.125s)

*** reverting m160313_153426_session_init

Fatal error: Uncaught ReflectionException: Class m160313_153426_session_init does not exist in /var/www/html/framework/di/Container.php on line 428

ReflectionException: Class m160313_153426_session_init does not exist in /var/www/html/framework/di/Container.php on line 428

Call Stack:
    0.0002     393360   1. {main}() /repo/vendor/phpunit/phpunit/phpunit:0
    0.0103    1400984   2. PHPUnit\TextUI\Command::main() /repo/vendor/phpunit/phpunit/phpunit:53
    0.0103    1401096   3. PHPUnit\TextUI\Command->run() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:148
    0.8595   62854568   4. PHPUnit\TextUI\TestRunner->doRun() /repo/vendor/phpunit/phpunit/src/TextUI/Command.php:195
    0.8627   63067776   5. PHPUnit\Framework\TestSuite->run() /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:546
 1415.6427  112118056   6. PHPUnit\Framework\TestSuite->run() /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php:755
 1424.3153  113225880   7. yiiunit\framework\rbac\DbManagerTestCase::tearDownAfterClass() /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
 1424.3153  113225880   8. yiiunit\framework\rbac\DbManagerTestCase::runConsoleAction() /var/www/html/tests/framework/rbac/DbManagerTestCase.php:87
 1424.3171  113256856   9. yii\console\Application->runAction() /var/www/html/tests/framework/rbac/DbManagerTestCase.php:62
 1424.3171  113256856  10. yii\console\Application->runAction() /var/www/html/framework/console/Application.php:180
 1424.3172  113257808  11. yiiunit\framework\console\controllers\EchoMigrateController->runAction() /var/www/html/framework/base/Module.php:528
 1424.3172  113259336  12. yiiunit\framework\console\controllers\EchoMigrateController->runAction() /var/www/html/framework/console/Controller.php:148
 1424.3174  113260016  13. yii\base\InlineAction->runWithParams() /var/www/html/framework/base/Controller.php:157
 1424.3174  113260768  14. call_user_func_array:{/var/www/html/framework/base/InlineAction.php:57}() /var/www/html/framework/base/InlineAction.php:57
 1424.3174  113261160  15. yiiunit\framework\console\controllers\EchoMigrateController->actionDown() /var/www/html/framework/base/InlineAction.php:57
 1424.4839  113269632  16. yiiunit\framework\console\controllers\EchoMigrateController->migrateDown() /var/www/html/framework/console/controllers/BaseMigrateController.php:261
 1424.4839  113269632  17. yiiunit\framework\console\controllers\EchoMigrateController->createMigration() /var/www/html/framework/console/controllers/BaseMigrateController.php:752
 1424.4840  113270008  18. yii\BaseYii::createObject() /var/www/html/framework/console/controllers/MigrateController.php:201
 1424.4840  113270008  19. yii\di\Container->get() /var/www/html/framework/BaseYii.php:349
 1424.4840  113270008  20. yii\di\Container->build() /var/www/html/framework/di/Container.php:156
 1424.4840  113270008  21. yii\di\Container->getDependencies() /var/www/html/framework/di/Container.php:364
 1424.4840  113270120  22. ReflectionClass->__construct() /var/www/html/framework/di/Container.php:428

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15-dev
| PHP version      |  7.2.2
| Operating system |alpine
