### ISSUE TITLE
MySQL 8.0.4 can't connect

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15741]
I try to use fresh mysql. I run tests. I have errors:
```sh
Next PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /var/www/html/framework/db/Connection.php:686
Stack trace:
#0 /var/www/html/framework/db/Connection.php(686): PDO->__construct('mysql:host=mysq...', 'travis', 'travis', NULL)
#1 /var/www/html/framework/db/Connection.php(612): yii\db\Connection->createPdoInstance()
#2 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(137): yii\db\Connection->open()
#3 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(50): yiiunit\framework\rbac\DbManagerTestCase::createConnection()
#4 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(82): yiiunit\framework\rbac\DbManagerTestCase::runConsoleAction('migrate/up', Array)
#5 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(702): yiiunit\framework\rbac\DbManagerTestCase::setUpBeforeClass()
#6 /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(546): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /repo/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#8 /repo/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#9 /repo/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#10 {main}
Caused by
PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /var/www/html/framework/db/Connection.php:686
Stack trace:
#0 /var/www/html/framework/db/Connection.php(686): PDO->__construct('mysql:host=mysq...', 'travis', 'travis', NULL)
#1 /var/www/html/framework/db/Connection.php(612): yii\db\Connection->createPdoInstance()
#2 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(137): yii\db\Connection->open()
#3 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(50): yiiunit\framework\rbac\DbManagerTestCase::createConnection()
#4 /var/www/html/tests/framework/rbac/DbManagerTestCase.php(82): yiiunit\framework\rbac\DbManagerTestCase::runConsoleAction('migrate/up', Array)
#5 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(702): yiiunit\framework\rbac\DbManagerTestCase::setUpBeforeClass()
#6 /repo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(546): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /repo/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#8 /repo/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#9 /repo/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#10 {main}
```
```yml
# Local run unit tests
# for docker-compose CLI like this manual https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/
#
# Important: run `composer install` before first time use
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint composer php update --no-dev -vvv
#
# run directly (can't terminate)
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint /repo/vendor/bin/phpunit php
#
# use shell
# docker-compose -f ~/projects/yii2-phpunit-docker-composition.yml run --rm --entrypoint bash php
# /repo/vendor/bin/phpunit

version: '2'
services:
  php:
    image: bscheshir/codeception:php7.2.2-fpm-alpine-yii2 #contain phpunit
    volumes:
      - ./yii2/tests/data/config-docker.php:/var/www/html/tests/data/config.php # use named connection for db
      - ./yii2:/var/www/html #src and tests shared to container
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
    depends_on:
      - pgsql
      - mysql
# example for pgsql
# also add ./tests/data/config.local.php
# <?php
# $config['databases']['pgsql']['dsn'] = 'pgsql:host=pgsql;port=5432;dbname=yii2advanced';
# $config['databases']['pgsql']['username'] = 'yii2advanced';
# $config['databases']['pgsql']['password'] = 'yii2advanced';
  pgsql:
    image: postgres:10.2
    environment:
      TZ: Europe/Moscow
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yiitest
      POSTGRES_USER: postgres
    networks:
      default:
        aliases:
         - postgres
  mysql:
    image: mysql:8.0.4
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yiitest
      MYSQL_USER: travis
      MYSQL_PASSWORD: travis

```

```sh
bash-4.4# /repo/vendor/bin/phpunit tests/framework/rbac/MySQLManagerCacheTest.php
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15-dev
| PHP version      | 7.2.2
| Operating system |
