### ISSUE TITLE
Unit Test not recognizing Yii:$app

### ISSUE THREAD

**Issue by mezlad** [yiisoft/yii2#15918]
I am having an issue where executing unit tests, the Yii:$app attribute is empty. my codeception.yml file has the following:

```
namespace: backend\tests

actor_suffix: Tester

paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support

settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M

modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
```

My test-local.php file has the following:

```php
<?php
return yii\helpers\ArrayHelper::merge(

    require __DIR__ . '/../../common/config/test-local.php',

    require __DIR__ . '/main.php',

    require __DIR__ . '/main-local.php',

    require __DIR__ . '/test.php',

    [
    ]

);
```

I am not sure what it is I am doing incorrectly.
