### ISSUE TITLE
Missing Icons in ActionColumn with Bootstrap 4.3.x

### ISSUE THREAD

**Issue by demonking** [yiisoft/yii2#17479]
With the Version 4 of Bootstrap, the icons were removed from the default library.

https://getbootstrap.com/docs/4.0/extend/icons/

### What steps will reproduce the problem?

AppAsset: 

~~~
            'yii\bootstrap4\BootstrapAsset',
            'yii\bootstrap4\BootstrapPluginAsset',
~~~

GridView: 
~~~
 
   <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'description:ntext',
            'image',

            [
                'class' => 'yii\grid\ActionColumn',
            ]
        ],
    ]); ?>


~~~
### What's expected?

Seeing the icons in the last column of the gridview.

### What do you get instead?

The css classes are not present in boostrap, so the icon's as not visible.

### Additional info

| Q                | A
| ---------------| ---
| Yii version   | 2
| PHP version  | 7.2
| Operating system | Linux Debian Stretch

For the Moment I use the awesome font library and a function which creates the Buttons:

~~~
        function createActionButtons($buttons=['view','update','delete']){
                $actionButtons = [];
                $actionButtons['update']= function($url,$model) {
                         return Html::a('<i class="fa fa-edit"></i>', $url, [
                                 'title' => Yii::t('app', 'edit')
                         ]);
                };
                $actionButtons['delete'] = function($url,$model) {
                         return Html::a('<i class="fas fa-trash"></i>', $url, [
                                 'title' => Yii::t('app', 'delete')
                         ]);
                };
                $actionButtons['view'] = function($url,$model) {
                         return Html::a('<i class="fas fa-eye"></i>', $url, [
                                 'title' => Yii::t('app', 'view')
                         ]);
                };
                return array_intersect_key($actionButtons,array_flip($buttons));
        }
~~~

**Comment by samdark** [comment]
Moved.

**Comment by rob006** [comment]
Related: https://github.com/yiisoft/yii-dataview/issues/10

**Comment by jai3232** [comment]
The easiest way is add the glyphicon to the Yii2. There is already yii2-bootstrap4-glyphicons by xtetis.
You can the see sort icon in the GridView as well.

**Comment by imitronov** [comment]
```css
.glyphicon {
    font-family: "Font Awesome 5 Free";
}
.glyphicon-eye-open:before {
    content: "\f06e";
    color: var(--success);
}
.glyphicon-pencil:before {
    content: "\f044";
    color: var(--primary);
}
.glyphicon-trash:before {
    content: "\f2ed";
    color: var(--danger);
}
```
