### ISSUE TITLE
composer.json issue with punycode1.3

### ISSUE THREAD

**Issue by shenril** [yiisoft/yii2#7020]
When i run composer update --dev --prefer-source
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.1 requires bower-asset/punycode 1.3.* -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/punycode 1.3.* -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/punycode 1.3.* -> no matching package found.
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2].
```
with composer.json :
```yaml
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/jquery": "1.10.*"
},
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```
Any idea to solve this ? Fresh installation of Yii2 seems fine which is a mystery to me...
