### ISSUE TITLE
LESS '--source-map' flag breaking the CSS output

### ISSUE THREAD

**Issue by saada** [yiisoft/yii2#7220]
Hey guys,

I'm having issues with the LESS compilation. The default configuration runs:
`lessc {from} {to} --no-color --source-map`
```css
body {
  background-color: red;
}
������������������������������������
```

By overriding it in the config/main.php like this
```php
'assetManager' => [
            'linkAssets' => true,
            'converter' => [
                'class' => 'yii\web\AssetConverter',
                'commands' => [
                    'less' => ['css', 'lessc {from} {to} --no-color'],
                ],
            ],
        ],
```
Notice the missing `--source-map` flag!
we get
```css
body {
  background-color: red;
}
```
